from src.books.schemas import BookModel
from datetime import datetime
import uuid

books = [
    BookModel(
        uid=uuid.uuid4(),
        title="Dilan 1990",
        author="Pidi Baiq",
        publisher="Pastel Books",
        published_date="2014-04-10",
        page_count=332,
        language="Indonesia",
        created_at=datetime.now(),
        updated_at=datetime.now(),
    ),
    BookModel(
        uid=uuid.uuid4(),
        title="Laskar Pelangi",
        author="Andrea Hirata",
        publisher="Bentang Pustaka",
        published_date="2005-09-01",
        page_count=529,
        language="Indonesia",
        created_at=datetime.now(),
        updated_at=datetime.now(),
    ),
    BookModel(
        uid=uuid.uuid4(),
        title="Bumi Manusia",
        author="Pramoedya Ananta Toer",
        publisher="Hasta Mitra",
        published_date="1980-08-25",
        page_count=535,
        language="Indonesia",
        created_at=datetime.now(),
        updated_at=datetime.now(),
    ),
    BookModel(
        uid=uuid.uuid4(),
        title="Negeri 5 Menara",
        author="Ahmad Fuadi",
        publisher="Gramedia Pustaka Utama",
        published_date="2009-07-01",
        page_count=424,
        language="Indonesia",
        created_at=datetime.now(),
        updated_at=datetime.now(),
    ),
    BookModel(
        uid=uuid.uuid4(),
        title="Perahu Kertas",
        author="Dee Lestari",
        publisher="Bentang Pustaka",
        published_date="2009-08-01",
        page_count=444,
        language="Indonesia",
        created_at=datetime.now(),
        updated_at=datetime.now(),
    ),
    BookModel(
        uid=uuid.uuid4(),
        title="Ayat-Ayat Cinta",
        author="Habiburrahman El Shirazy",
        publisher="Republika",
        published_date="2004-12-01",
        page_count=414,
        language="Indonesia",
        created_at=datetime.now(),
        updated_at=datetime.now(),
    ),
    BookModel(
        uid=uuid.uuid4(),
        title="Sang Pemimpi",
        author="Andrea Hirata",
        publisher="Bentang Pustaka",
        published_date="2006-07-01",
        page_count=292,
        language="Indonesia",
        created_at=datetime.now(),
        updated_at=datetime.now(),
    ),
    BookModel(
        uid=uuid.uuid4(),
        title="Ronggeng Dukuh Paruk",
        author="Ahmad Tohari",
        publisher="Gramedia Pustaka Utama",
        published_date="1982-01-01",
        page_count=432,
        language="Indonesia",
        created_at=datetime.now(),
        updated_at=datetime.now(),
    ),
    BookModel(
        uid=uuid.uuid4(),
        title="Cantik Itu Luka",
        author="Eka Kurniawan",
        publisher="Gramedia Pustaka Utama",
        published_date="2002-11-20",
        page_count=482,
        language="Indonesia",
        created_at=datetime.now(),
        updated_at=datetime.now(),
    ),
    BookModel(
        uid=uuid.uuid4(),
        title="Gadis Kretek",
        author="Ratih Kumala",
        publisher="Gramedia Pustaka Utama",
        published_date="2012-03-01",
        page_count=274,
        language="Indonesia",
        created_at=datetime.now(),
        updated_at=datetime.now(),
    ),
]
