"""add min_length rule to the password_hash

Revision ID: c3d6606220c0
Revises: 0a5a5b7a3c7f
Create Date: 2025-09-03 23:05:45.980490

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c3d6606220c0'
down_revision: Union[str, Sequence[str], None] = '0a5a5b7a3c7f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
